### ISSUE TITLE
AceGUI 3: 'SetBackdrop' error when attempting to view/edit display properties of bar

### ISSUE THREAD

**Issue by Knaledge** [the-rebel-Mermaid/ChocolateBar#4]
Just raising awareness of this issue, perhaps sourced in AceGUI 3. 

https://www.curseforge.com/wow/addons/ace3/issues/560

**Comment by Nevcairiel** [comment]
The issue comes from bundling an out-of-date version of AceGUI-3.0-SharedMediaWidgets, the primary problem being that the updated version was not tagged, and thus not being pulled in by the packager when requesting the latest tag.

I have however since then tagged SharedMediaWidgets so hopefully any future releases will include it.

**Comment by Knaledge** [comment]
Thank @Nevcairiel ! Hopefully that latest version will get pulled in when the various addon authors recompile for future updates

**Comment by Knaledge** [comment]
(Leaving this open for just a bit while folks trickle in from Curseforge/WoWInterface, namely since many very popular addons (of which ChocolcateBar finds itself among) make use of AceGUI-3.0-SharedMediaWidgets - and those users may run into this as a result (it's certainly how I, and several others I play with, ran into it). 

I've set a reminder to close this out in 3 days (if it has not been closed by then already).
